# Permissions:
#     - Reload Command: "prisoncore.admin"
#     - Join Format: "prisoncore.join.vip"
#     - Enchant Add: prisoncore.enchants.add"
#
chat-format: "%vault_prefix%%player%%vault_suffix% &8» %chat-colour%%message%"
# Permission "prisoncore.join.vip"
join-format: "&8(&a+&8) %vault_prefix%&7%player%%vault_suffix%"
quit-format: "&8(&c-&8) %vault_prefix%&7%player%%vault_suffix%"
# The World Name with all the Mines in.
mines-world-name: "world"
# Block Absorber
ba-item: "shulker_shell"
ba-item-name: "&a&lBLOCK ABSORBER"
# Split with ;
absorb-able-blocks: "stone;deepslate;coal_ore;deepslate_coal_ore;iron_ore;deepslate_iron_ore;gold_ore;deepslate_gold_ore;redstone_ore;deepslate_redstone_ore;lapis_ore;deepslate_lapis_ore;diamond_ore;deepslate_diamond_ore"
absorb-able-blocks-values: "0.1;0.1;0.2;0.2;0.3;0.3;0.4;0.4;0.5;0.5;0.6;0.6;0.7;0.7"
absorb-able-blocks-interval: 30 # In seconds
absorb-sell-message: "&a&l+&c&l$%total_amount%"