# Permissions:
#     - Reload Command: "prisoncore.admin"
#     - Join Format: "prisoncore.join.vip"
#
chat-format: "%vault_prefix%%player%%vault_suffix% &8» %chat-colour%%message%"
# Permission "prisoncore.join.vip"
join-format: "&8(&a+&8) &7%player%"
quit-format: "&8(&c-&8) &7%player%"
# Split with ;
absorb-able-blocks: "stone;coal_ore;iron_ore"
# The World Name with all the Mines in.
mines-world-name: "world"
# Block Absorber
ba-item: "beacon"
ba-item-name: "&a&lBLOCK ABSORBER"
