name: PrisonCore
version: '${project.version}'
main: uk.co.tmdavies.prisoncore.PrisonCore
api-version: 1.19
authors: [ Carbonate, DoomFly3215 ]
softdepend: [ PlaceholderAPI, Vault ]
description: Prison Core TTB Prison
commands:
  core:
    description: Main Command
  ce:
    description: Custom Enchant Command
permissions:
  prisoncore.admin:
    default: op
  prisoncore.join.vip:
    default: op
